# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f89ba41672dcf70ef366553605b7be66"
name = "profile-portal-login-poc"
handle = "profile-portal-login-poc"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "mark-tomlinson-1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
